### ISSUE TITLE
it has here are problems when using in recyclerview item 

### ISSUE THREAD

**Issue by ImportEffort** [devsideal/ReadMoreOption#3]
There are problems when using in recyclerview item . The problem is that the expanded state is reclaimed after the item is reclaimed.

**Comment by devendroid** [comment]
Do the following when using with RecyclerView/ListView -
1. Disable animation like `expandAnimation(false)`
2. Don't use text length using line no, use like `textLength(300,ReadMoreOption.TYPE_CHARACTER)`

Because these are [known issues](https://github.com/devendroid/ReadMoreOption#known-issue) i mentioned in doc.
